const PRODUCTS = [
  { id: 1, name: 'Dragon Roll', category: 'rolls', price: 18.50, badge: 'popular',
    img: 'images/rest_1.jpg',
    desc: 'Shrimp tempura, cucumber, topped with avocado and tobiko.' },
  { id: 2, name: 'Salmon Aburi', category: 'sushi', price: 16.00, badge: null,
    img: 'images/rest_2.jpg',
    desc: 'Flame-seared salmon nigiri with ponzu and microgreens.' },
  { id: 3, name: 'Rainbow Roll', category: 'rolls', price: 21.00, badge: 'new',
    img: 'images/rest_3.jpg',
    desc: 'California base topped with assorted sashimi and avocado.' },
  { id: 4, name: 'Spicy Tuna Roll', category: 'rolls', price: 14.50, badge: null,
    img: 'images/rest_4.jpg',
    desc: 'Fresh tuna, sriracha mayo, cucumber and sesame seeds.' },
  { id: 5, name: 'Salmon Sashimi', category: 'sushi', price: 22.00, badge: null,
    img: 'images/rest_5.jpg',
    desc: '8 pieces of premium Atlantic salmon, served with wasabi & gari.' },
  { id: 6, name: 'Omakase Platter', category: 'specials', price: 68.00, badge: 'chef',
    img: 'images/rest_6.jpg',
    desc: "Chef's daily selection — 12 pieces nigiri & 2 specialty rolls." },

  { id: 7, name: 'Tonkotsu Ramen', category: 'mains', price: 17.50, badge: 'popular',
    img: 'images/rest_1.jpg',
    desc: 'Rich pork bone broth, chashu, soft egg, bamboo shoots, nori.' },
  { id: 8, name: 'Chicken Katsu Don', category: 'mains', price: 15.00, badge: null,
    img: 'images/rest_2.jpg',
    desc: 'Crispy chicken katsu over rice in a dashi egg sauce.' },
  { id: 9, name: 'Miso Ramen', category: 'mains', price: 16.50, badge: null,
    img: 'images/rest_3.jpg',
    desc: 'White miso broth with corn, butter, bean sprouts, and chashu.' },
  { id: 10, name: 'Gyudon Bowl', category: 'mains', price: 14.00, badge: null,
    img: 'images/rest_4.jpg',
    desc: 'Sliced beef and onion simmered in sweet soy sauce over rice.' },

  { id: 11, name: 'Edamame', category: 'starters', price: 5.50, badge: null,
    img: 'images/rest_5.jpg',
    desc: 'Salted young soybeans, lightly steamed.' },
  { id: 12, name: 'Gyoza (6 pcs)', category: 'starters', price: 9.00, badge: 'popular',
    img: 'images/rest_6.jpg',
    desc: 'Pan-fried pork & cabbage dumplings with ponzu dipping sauce.' },
  { id: 13, name: 'Karaage Chicken', category: 'starters', price: 11.50, badge: null,
    img: 'images/rest_1.jpg',
    desc: 'Japanese fried chicken with kewpie mayo and lemon.' },
  { id: 14, name: 'Miso Soup', category: 'starters', price: 4.00, badge: null,
    img: 'images/rest_2.jpg',
    desc: 'Traditional white miso soup with tofu, wakame and scallion.' },

  { id: 15, name: 'Wagyu Teppanyaki', category: 'specials', price: 58.00, badge: 'chef',
    img: 'images/rest_3.jpg',
    desc: 'Grade A5 wagyu beef, grilled tableside with seasonal vegetables.' },
  { id: 16, name: 'Bento Deluxe', category: 'specials', price: 32.00, badge: 'new',
    img: 'images/rest_4.jpg',
    desc: 'Chicken teriyaki, 4pc sushi, miso, salad, rice, fruit.' },

  { id: 17, name: 'Matcha Latte', category: 'drinks', price: 6.50, badge: null,
    img: 'images/rest_5.jpg',
    desc: 'Ceremonial grade matcha with oat milk, lightly sweetened.' },
  { id: 18, name: 'Sake (200ml)', category: 'drinks', price: 12.00, badge: null,
    img: 'images/rest_6.jpg',
    desc: 'Junmai daiginjo served chilled — floral and crisp.' },
  { id: 19, name: 'Mochi Ice Cream', category: 'desserts', price: 8.00, badge: null,
    img: 'images/rest_1.jpg',
    desc: 'Three pieces — matcha, strawberry, and black sesame.' },
  { id: 20, name: 'Taiyaki Waffle', category: 'desserts', price: 9.50, badge: 'new',
    img: 'images/rest_2.jpg',
    desc: 'Fish-shaped waffle with red bean or custard filling, ice cream.' },
];

const CATEGORIES = [
  { id: 'all',      label: 'All Items' },
  { id: 'specials', label: '⭐ Specials' },
  { id: 'rolls',    label: 'Sushi Rolls' },
  { id: 'sushi',    label: 'Nigiri & Sashimi' },
  { id: 'mains',    label: 'Mains' },
  { id: 'starters', label: 'Starters' },
  { id: 'drinks',   label: 'Drinks' },
  { id: 'desserts', label: 'Desserts' },
];
